# Generated by Django 4.2.2 on 2023-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0003_carrinho'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='atual',
            field=models.CharField(default='nulo', max_length=50),
        ),
    ]
